# Generated by Django 2.2 on 2019-05-01 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barracks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bathroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bathroom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('status', models.CharField(default='', max_length=10)),
                ('bathroom_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='supply.Bathroom')),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('barracks_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='supply.Barracks')),
            ],
        ),
        migrations.AddField(
            model_name='bathroom',
            name='floor_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='supply.Floor'),
        ),
    ]
