# Generated by Django 2.2 on 2019-04-26 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0003_auto_20190425_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bathroom',
            name='gender',
        ),
    ]
